spring.application.name=multitenancy2

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://neondb_owner:npg_tehi6WGdn3mC@ep-winter-bird-at47vv7r-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_tehi6WGdn3mC}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true